import { AlertTriangle, GraduationCap, ListChecks, Sparkles } from "lucide-react";
import type { Route } from "./+types/insights";
import Navbar from "~/components/Navbar";
import MobileNavbar from "~/components/MobileNavbar";
import { recurringPatterns, recommendedTechnologies, learningRoadmap } from "~/constants";
import { requireUser } from "~/lib/session.server";

export async function loader({ request }: Route.LoaderArgs) {
    const user = await requireUser(request);
    return { user };
}

export function meta({ }: Route.MetaArgs) {
    return [{ title: "Insights — Applyze" }];
}

export default function Insights() {
    const sortedPatterns = [...recurringPatterns].sort((a, b) => b.frequency - a.frequency);
    const sortedRoadmap = [...learningRoadmap].sort((a, b) => a.order - b.order);
    const totalApplications = 13;

    return (
        <main className="bg-[url('/images/bg-main.svg')] bg-cover">
            <Navbar />
            <MobileNavbar />
            <section className="main-section items-stretch">
                <div className="w-full max-w-300 mx-auto">
                    <h1 className="dashboard-title md:text-3xl tracking-wide">Insights Worth Knowing</h1>
                    <p className="dashboard-subtitle">Your biggest recurring technical gaps across applications, ranked by how often they show up.</p>
                    <p className="mt-2 flex items-center gap-1.5 text-xs text-dark-200">
                        <Sparkles className="h-3.5 w-3.5 shrink-0 text-[#606beb]" />
                        Content generated by AI using the information from your profile and job analyses.
                    </p>
                </div>

                <div className="mx-auto grid w-full max-w-300 grid-cols-1 items-start gap-4 lg:grid-cols-2">
                    <div className="profile-category-card bg-blue-100 lg:col-span-2">
                        <h3 className="flex items-center gap-2 text-base font-semibold">
                            <AlertTriangle className="h-4 w-4 text-[#606beb]" />
                            Where the gaps keep showing up
                        </h3>
                        <p className="text-sm text-dark-200">
                            We looked across all {totalApplications} of your applications to find the gaps that keep
                            coming up more than once — worth addressing before your next round, not after another
                            rejection points it out.
                        </p>
                        {sortedPatterns.map((pattern) => (
                            <div key={pattern.id} className="profile-entry-card">
                                <div className="flex items-center justify-between gap-2">
                                    <p className="font-semibold text-black">{pattern.title}</p>
                                    <span className="shrink-0 rounded-full bg-white px-2.5 py-0.5 text-xs font-medium text-dark-200">
                                        {pattern.frequency} application{pattern.frequency === 1 ? "" : "s"}
                                    </span>
                                </div>
                                <p className="text-xs text-dark-200">{pattern.companies.join(", ")}</p>
                                <p className="text-sm text-dark-200">{pattern.note}</p>
                            </div>
                        ))}
                    </div>

                    <div className="profile-category-card bg-violet-100">
                        <h3 className="flex items-center gap-2 text-base font-semibold">
                            <GraduationCap className="h-4 w-4 text-[#606beb]" />
                            Technologies to Study
                        </h3>
                        <p className="text-sm text-dark-200">
                            Of the gaps above, these are worth actively studying for — the rest are either hard
                            eligibility requirements or too broad to "study" your way into directly.
                        </p>
                        {recommendedTechnologies.map((tech) => (
                            <div key={tech.id} className="profile-entry-card">
                                <p className="font-semibold text-black">{tech.name}</p>
                                <p className="text-sm text-dark-200">{tech.reason}</p>
                            </div>
                        ))}
                    </div>

                    <div className="profile-category-card bg-teal-100">
                        <h3 className="flex items-center gap-2 text-base font-semibold">
                            <ListChecks className="h-4 w-4 text-[#606beb]" />
                            Learning Roadmap
                        </h3>
                        <p className="text-sm text-dark-200">
                            Tackle these in order — each step is sequenced by how much it unblocks and how
                            self-contained it is to finish.
                        </p>
                        {sortedRoadmap.map((step, index) => (
                            <div key={step.id} className="profile-entry-card flex-row items-start gap-3">
                                <span className="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-[#606beb] text-xs font-semibold text-white">
                                    {index + 1}
                                </span>
                                <div>
                                    <p className="font-semibold text-black">{step.title}</p>
                                    <p className="text-sm text-dark-200">{step.description}</p>
                                </div>
                            </div>
                        ))}
                    </div>
                </div>
            </section>
        </main>
    );
}
